name: Télécharger les données de Dofus

on:
  workflow_dispatch:

jobs:
  download_dofus_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout le code du dépôt
      uses: actions/checkout@v2

    - name: Installer doduda
      run: |
        curl -s https://get.dofusdu.de/doduda | sh

    - name: Télécharger les données de Dofus
      run: |
        doduda --full --output resultats

    - name: Vérifier le contenu du dossier 'resultats'
      run: |
        ls -l resultats
