name: Exécution de Doduda

on:
  workflow_dispatch:

jobs:
  run_doduda:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code du dépôt
      uses: actions/checkout@v2

    - name: Télécharger le binaire doduda
      run: |
        curl -s https://get.dofusdu.de/doduda | sh

    - name: Télécharger les données Dofus
      run: |
        # 1. Télécharge les données nécessaires dans le dossier ./data (par défaut)
        doduda --output ./data
        
        # 2. Exécute le map après avoir téléchargé les fichiers
        doduda map --input ./data --output ./resultats

    - name: Upload des résultats en tant qu'artefact
      uses: actions/upload-artifact@v4
      with:
        name: resultats-doduda
        path: resultats/
