name: Exécution de Doduda

on:
  workflow_dispatch:  # Permet d'exécuter le workflow manuellement via l'interface GitHub

jobs:
  run_doduda:
    runs-on: ubuntu-latest  # Utilise une machine Ubuntu pour exécuter le workflow

    steps:
    - name: Checkout du code du dépôt
      uses: actions/checkout@v2

    - name: Télécharger le binaire doduda
      run: |
        curl -s https://get.dofusdu.de/doduda | sh

    - name: Créer un fichier test pour simuler les résultats
      run: |
        mkdir -p resultats
        echo '{"monster":"Bouftou","level":5,"hp":30}' > resultats/test_monster.json
        echo "Fichier de test créé dans resultats/"


    - name: Sauvegarder le résultat
      run: |
        mkdir resultats
        shopt -s extglob
        mv !(resultats) resultats/
        echo "Les résultats sont stockés dans le dossier resultats."

    - name: Upload des résultats en tant qu'artefact
      uses: actions/upload-artifact@v4
      with:
        name: resultats-doduda
        path: resultats/
