name: Exécution de Doduda

on:
  workflow_dispatch:  # Lance manuellement via GitHub

jobs:
  run_doduda:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout le code du dépôt
      uses: actions/checkout@v2

    # Pas besoin d'installer Docker !

    - name: Vérifier la version de Docker (déjà installé)
      run: docker --version

    - name: Télécharger le binaire doduda
      run: |
        curl -s https://get.dofusdu.de/doduda | sh

    - name: Exécuter la commande doduda
      run: |
        doduda --full

    - name: Sauvegarder le résultat
      run: |
        mkdir resultats
        shopt -s extglob
        mv !(resultats) resultats/
        echo "Les résultats sont stockés dans le dossier resultats."

