name: Exécution de Doduda

on:
  workflow_dispatch:  # Permet d'exécuter le workflow manuellement via l'interface GitHub

jobs:
  run_doduda:
    runs-on: ubuntu-latest  # Utilise une machine Ubuntu pour exécuter le workflow

    steps:
    - name: Checkout du code du dépôt
      uses: actions/checkout@v2

    - name: Télécharger le binaire doduda
      run: |
        curl -s https://get.dofusdu.de/doduda | sh

    - name: Télécharger les données Dofus 2
      run: |
        # Utilise doduda pour télécharger toutes les données de Dofus 2 sans Docker
        doduda --full --game dofus2 --download

    - name: Télécharger les données Dofus 3 (avec Docker)
      run: |
        # Utilise doduda avec Docker pour récupérer toutes les données de Dofus 3
        doduda --full --game dofus3 --download

    - name: Sauvegarder les résultats
      run: |
        # Créer un dossier resultats et déplacer les données téléchargées
        mkdir resultats
        mv * resultats/
        echo "Les résultats sont stockés dans le dossier resultats."


