name: Doduda Workflow

on:
  push:
    branches:
      - main

jobs:
  run-doduda:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Doduda command
      run: |
        curl -s https://get.dofusdu.de/doduda | sh
        # Optionally, add more commands to use Doduda
