name: Exécution de Doduda

on:
  workflow_dispatch:  # Permet d'exécuter le workflow manuellement via l'interface GitHub

jobs:
  run_doduda:
    runs-on: ubuntu-latest  # Utilise une machine Ubuntu pour exécuter le workflow

    steps:
    - name: Checkout du code du dépôt
      uses: actions/checkout@v2

    - name: Télécharger le binaire doduda
      run: |
        curl -s https://get.dofusdu.de/doduda | sh

    - name: Télécharger les données Dofus 
      run: |
         doduda
         doduda map


    - name: Sauvegarder les résultats
      run: |
        # Créer un dossier resultats et déplacer les données téléchargées
        mkdir resultats
        mv * resultats/
        echo "Les résultats sont stockés dans le dossier resultats."
