name: Exécution de Doduda

on:
  workflow_dispatch:

jobs:
  run_doduda:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code du dépôt
      uses: actions/checkout@v2

    - name: Télécharger le binaire doduda
      run: |
        curl -s https://get.dofusdu.de/doduda | sh

    - name: Télécharger les données Dofus
      run: |
        # 1. Télécharge les données nécessaires dans le dossier ./resultats
        doduda --output ./resultats
        
        # 2. Exécute le map après avoir téléchargé les fichiers
        doduda map --output ./resultats

    - name: Upload des résultats en tant qu'artefact
      uses: actions/upload-artifact@v4
      with:
        name: resultats-doduda
        path: resultats/

  display_results:
    runs-on: ubuntu-latest
    needs: run_doduda

    steps:
    - name: Checkout du code du dépôt
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: resultats-doduda
        path: ./artifact

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install streamlit

    - name: Run Streamlit
      run: streamlit run streamlit_app.py
