name: Exécution de Doduda

on:
  workflow_dispatch:

jobs:

display_results:
    runs-on: ubuntu-latest
    needs: run_doduda

    steps:
    - name: Checkout du code du dépôt
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: resultats-doduda
        path: ./artifact

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install streamlit

    - name: Run Streamlit
      run: streamlit run streamlit_app.py
